spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thistle
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
    mongodb:
      database: thistle
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
